import numpy as np
import os

def read_matrix(file_name):
    with open(file_name, 'r') as f:
        lines = f.readlines()
    lines = [line.strip() for line in lines]
    lines = [line for line in lines if line]
    lines = [line.split() for line in lines]
    lines = [[float(x) for x in line] for line in lines]
    return np.array(lines)


def read_tetgen_file(node_file_name, ele_file_name):
    node_file = read_matrix(node_file_name)
    ele_file = read_matrix(ele_file_name)
    verts = node_file[:, 1:]
    eles = ele_file[:, 1:]
    return verts, eles

def generate_tet_mesh(verts, eles, file_name):
    with open(file_name, 'w') as f:
        f.write('# Generated by generate_tet_mesh() in read_matrix.py\n')
        f.write('# vertices\n')
        f.write('%d\n' % len(verts))
        for vert in verts:
            f.write('%f %f %f\n' % tuple(vert))
        f.write('# elements\n')
        f.write('%d\n' % len(eles))
        for ele in eles:
            f.write('%d %d %d %d\n' % tuple(ele))
